// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $anger_mode from "./routes/anger-mode.tsx";
import * as $anxiety_mode from "./routes/anxiety-mode.tsx";
import * as $api_grok_reflection from "./routes/api/grok-reflection.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $apps_facebook from "./routes/apps/facebook.tsx";
import * as $apps_snapchat from "./routes/apps/snapchat.tsx";
import * as $apps_tiktok from "./routes/apps/tiktok.tsx";
import * as $apps_twitter from "./routes/apps/twitter.tsx";
import * as $apps_whatsapp from "./routes/apps/whatsapp.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $AngerManagement from "./islands/AngerManagement.tsx";
import * as $AnxietySimulator from "./islands/AnxietySimulator.tsx";
import * as $apps_FacebookPumzika from "./islands/apps/FacebookPumzika.tsx";
import * as $apps_SnapchatPumzika from "./islands/apps/SnapchatPumzika.tsx";
import * as $apps_TikTokPumzika from "./islands/apps/TikTokPumzika.tsx";
import * as $apps_TwitterPumzika from "./islands/apps/TwitterPumzika.tsx";
import * as $apps_WhatsAppPumzika from "./islands/apps/WhatsAppPumzika.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/anger-mode.tsx": $anger_mode,
    "./routes/anxiety-mode.tsx": $anxiety_mode,
    "./routes/api/grok-reflection.ts": $api_grok_reflection,
    "./routes/api/joke.ts": $api_joke,
    "./routes/apps/facebook.tsx": $apps_facebook,
    "./routes/apps/snapchat.tsx": $apps_snapchat,
    "./routes/apps/tiktok.tsx": $apps_tiktok,
    "./routes/apps/twitter.tsx": $apps_twitter,
    "./routes/apps/whatsapp.tsx": $apps_whatsapp,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/AngerManagement.tsx": $AngerManagement,
    "./islands/AnxietySimulator.tsx": $AnxietySimulator,
    "./islands/apps/FacebookPumzika.tsx": $apps_FacebookPumzika,
    "./islands/apps/SnapchatPumzika.tsx": $apps_SnapchatPumzika,
    "./islands/apps/TikTokPumzika.tsx": $apps_TikTokPumzika,
    "./islands/apps/TwitterPumzika.tsx": $apps_TwitterPumzika,
    "./islands/apps/WhatsAppPumzika.tsx": $apps_WhatsAppPumzika,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
